apiVersion: v1
kind: Service
metadata:
  name: service-hello-python
  labels:
    name: service-hello-python

spec:
  type: LoadBalancer
  ports:
    - targetPort: 8000
      port: 80
  selector:
    app: hello-python